from allauth.socialaccount.adapter import DefaultSocialAccountAdapter

class CustomSocialAccountAdapter(DefaultSocialAccountAdapter):
    def populate_user(self, request, sociallogin, data):
        user = super().populate_user(request, sociallogin, data)

        first_name = data.get("given_name") or data.get("first_name")
        last_name = data.get("family_name") or data.get("last_name")

        # Set first name + last name
        if first_name:
            user.first_name = first_name
        if last_name:
            user.last_name = last_name

        # Use first name as username
        if first_name:
            user.username = first_name.lower()

        return user


# this prevents 3rd party sign-up page because username is autogenerated now. 