# Generated by Django 4.2.23 on 2025-09-22 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_food_created_at_food_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
